---
title: "Raspberry Pi and Environmental Monitoring"
author: "Marc Los Huertos and Anna Burns"
date: "5/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

## What is Rasberry Pi?

The Raspberry Pi is an tiny computer, that includes a tiny processor, a bit of memory, a slot for an SD card, and some input/output jacks, e.g. HDMI, USB, headphone, camera, and pin header for various sensors.

## Why use Raspberry Pi?

The Pi has a lot of functionality and flexibility for develop monitoring of environmental parameters. 

## Uses in Environmental Science

### Weather and Climate Change



### Air Pollution Monitoring

### Soil Water Monitoring and Irrigation Control

https://fyi.extension.wisc.edu/cropirrigation/files/2015/03/Methods.to_.Monitor.Soil_.Moisture.pdf

### Conservation 

Conservation biologists use a wide range of instruments to track and monitor wildlife (camera traps, active (radio) and passive (RIF) transmitters). In addition the use of cameras are used to evaluate plant health and diversity (spectral analysis). 



## Resources

### Raspberry Pi 

The Raspberry was created to help non-technical youth to learn computer and robotics. The Raspberry Pi was an unexpected success and now the Pi is one of the most important minaturized computers for a wide range of projects.  

The [RaspberryPi.org](https://www.raspberrypi.org/) has tutorials, software updates, and example projects. 

### Video Tutorials

[Amazon Prime -- Introducing Rasberry Pi History, Models, and Uses](https://www.amazon.com/gp/video/detail/B07ZTR6ST2/ref=atv_dp_share_cu_r)

## Projects General-purpose input/output Examples

### Weather and Climate

[Thermocouples Sensors](https://www.omega.com/en-us/resources/thermocouples])

### Air Quality

#### Sensors

- Particulate Matter
- NOx
- O3
- CO
- Temperature/Humidity

#### Software

- Python Script

### Soil Moisture

[cheap version](https://tutorials-raspberrypi.com/measuring-soil-moisture-with-raspberry-pi/)

[Raspberry 3 and Capacitance Sensors](https://www.switchdoc.com/2018/11/tutorial-capacitive-moisture-sensor-grove/)

[moisture-sensor-dfrobot](https://tutorials-raspberrypi.com/raspberry-pi-capacitive-spoil-moisture-sensor-dfrobot-gravity/)


### Wildlife

Poacher Cam v7, Chris Kline, panthera.org