---
title: "Arduino Guide"
author: "Anna Madison Burns"
date: "6/2/2020"
output: html_document
---

# Background

## What is Arduino?

Arduino is an open-source electronics platform that transforms inputs to outputs.

## Why use Arduino?

Arduino is inexpensive and accessible, so it is a useful tool both for new and experienced programmers alike.  It fits comfortably in educational and research settings, and includes a useful community hub for projects and advice.  

## Programming Language

Arduino uses IDE (Arduino software) that can be used through a web editor.

https://create.arduino.cc/projecthub/Arduino_Genuino/getting-started-with-arduino-web-editor-on-various-platforms-4b3e4a

This is a link to instructions on how to begin programming your Arduino platform.  

## Using Arduino with Raspberry Pi

https://www.sciencedirect.com/science/article/pii/S1877050914009144 

## Uses in Environmental Science

https://create.arduino.cc/projecthub?category=sensors-environment&sort=recent -> this is the hub on Arduino's community boards for environmental projects with Arduino.

The book "Environmental Monitoring in Arduino" (by Emily Gertz and Patrick DiJusto) is available in an ebook format through the Claremont Colleges Library.

### Weather Stations

http://cactus.io/projects/weather/arduino-weather-station

https://create.arduino.cc/projecthub/Kyrpy/iot-weather-station-adbff4?ref=platform&ref_id=424_recent___&offset=6 -> a project for a home garden weather station.

### Indoor air quality

https://create.arduino.cc/projecthub/east-west-university/indoor-air-quality-monitoring-system-5b5244

https://www.electronics-lab.com/project/arduino-air-quality-meter/

### Water flow

https://create.arduino.cc/projecthub/SAROSH_AHMAD/water-flow-rate-and-volume-measurement-using-arduino-in-2020-5377df?ref=platform&ref_id=424_recent___&offset=4

### Soil

https://create.arduino.cc/projecthub/hubmartin/soil-sensor-with-arduino-esp8266-esp32-2bc942?ref=platform&ref_id=424_recent___&offset=4

(Arduino used with a soil sensor)



