---
title: "Drone Background"
author: "Anna Madison Burns"
date: "7/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# The Air Circulation Problem

Idea: open up both sides, but have fan w/ adjustable speed pulling air OUT on one of the sides, thus creating a vaccuum of sorts and allowing air to cycle in as the stagnant air leaves.  Can purchase small fans w/ adjustable power... run series of tests measuring readings at different speeds using the fan vs. when the sensor is outside the box to see most effective speed for getting accurate readings.

- how to pull air through

- what rate to pull air through

### Resources for air flow readers

https://www.banggood.com/Diesel-MAF-Mass-Air-Flow-Meter-Sensor-For-Benz-CE-Class-02-08-p-966600.html?rmmds=detail-left-hotproducts__7&cur_warehouse=CN

https://www.banggood.com/5-Pins-MAF-Mass-Air-Flow-Sensor-Meter-For-Chevrolet-2001-2007-GMC-6_6L-p-1104122.html?rmmds=detail-left-hotproducts__6&cur_warehouse=CN

https://www.banggood.com/Mass-Air-Flow-Sensor-Meter-MAF-For-Citroen-Xsara-For-Fiat-For-Peugeot-306-307-406-806-p-1249805.html?rmmds=detail-left-hotproducts__3&cur_warehouse=CN

https://www.banggood.com/FS300A-G34-DN20-Hall-Flow-Sensor-6-Points-Air-Conditioning-Water-Flow-Sensor-1-60LMIN-p-1476459.html?rmmds=buy&cur_warehouse=CN

https://www.pce-instruments.com/us/measuring-instruments/test-meters/air-flow-meter-pce-instruments-air-flow-meter-pce-ta-30-det_2131215.htm?_list=kat&_listpos=1 (this one seems best, but is also most expensive)

https://www.mcmaster.com/airflow-meters/flowmeters-for-air-8/


### Information about Air Flow, Mechanized Air Flow, Ventilation, etc.

https://iaqscience.lbl.gov/vent-info

https://www.iotacommunications.com/blog/how-can-you-improve-indoor-air-quality/

https://www.epa.gov/sites/production/files/2014-08/documents/ventilation_factsheet.pdf

https://nchh.org/information-and-evidence/learn-about-healthy-housing/health-hazards-prevention-and-solutions/ventilation-and-indoor-air-quality/

https://www.sciencedirect.com/science/article/abs/pii/S0021863496901407

https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/ldv-measurements-of-an-airsolid-twophase-flow-in-a-horizontal-pipe/C0896F3BE25B91382F9112C1804E3F57

https://www.sciencedirect.com/science/article/abs/pii/S153751100800055X

# What we need

### Something to put the Pi/sensors in

https://cpc.farnell.com/olan/ol20112/box-ip55-glanded-150x110x70mm/dp/EN82191 

Datasheet: http://www.farnell.com/datasheets/1513687.pdf

This already comes with air holes, and is what is used for the Raspberry Pi's tutorial on a home weather station. It is inexpensive, and made of thermoplastic (so it's light - only .22 kg).  It has four screw holes on the bottom to fasten it, but we could attach it to the anti-vibration pad in another way if that is not conducive.  2.76" x 5.91" x 4.33".

### A way to circulate air into the sensors

If we get the box above, the problem is fixed for us; we can remove the side plugs to allow air to circulate through.  Otherwise, we can look into the tubing - I didn't find where it mentioned this?

### A way to attach the Pi/sensors to the drone

Velcro, zip ties, double sided tape (this seems iffy), or screw it to the anti-vibration pad.  I think a combination of velcro and zip ties would be secure.

### A way to connect to a computer to begin the sensor

Wifi dongle - https://www.amazon.com/Adapter-Wireless-Network-External-OS10-6-10-13/dp/B019SRBUNG would this work? Need to look more into how this functions (we need the computer and the Pi to be on the same Wifi network, can we create a hotspot? How?)

### Something to fasten the connectors more tightly

Printed circuit board OR Adafruit Perma-Proto Hat (used in https://projects.raspberrypi.org/en/projects/build-your-own-weather-station/10 , this seems like it could totally work for us! Can we solder our connecting wires shorter, or do we need to buy those?)

# Sources and Info

### Furmanova et al.'s "The Mobile Environment Monitoring System"

Link: http://ceur-ws.org/Vol-2300/Paper44.pdf

- PCB (printed circuit board):  "Tracing of the printing unit was carried out on a basis of an electric schematic diagram in the easyEDA system.  

### Adafruit Perma-Proto HAT for Mini Pi Kit - No EEPROM

Link: https://www.adafruit.com/product/2310?PageSpeed=noscript&gclid=CjwKCAjwsO_4BRBBEiwAyagRTQlFrwAQD-yHQiCUn9EkWyqoN04rhlgcNxCR1CWLppUoJAZe5dbNixoCL4YQAvD_BwE 

This is a hat we can solder units onto that then fits over the Pi.  Doesn't look like this particular one will work for the number of connections we need, but good to know that it's out there.

### How to Make a 20V to 12V to 5V Convertor Using 7812 IC and 7085

Link:  https://www.youtube.com/watch?v=NutYeB8H5WE

Our drone puts out 20V, and has a UART socket that has a 7.7V output.  This means we need to reduce the voltage in order for our Pi to run off of our drone's power.  This video builds one, but **can we find one that is premade**?

Premade options - 

https://www.amazon.com/9V-20V-Step-down-Supply-Converter-Module/dp/B01H9702ZY -> this has USB input and output, will this work with the drone or do we need UART?  USB can be converted to work with the Pi (M-F USB adaptor to connect to Pi's power output).  This is super cheap.

https://www.mouser.com/ProductDetail/CUI-Inc/PQDE6W-Q24-S5-T?qs=fAHHVMwC%252BbijFYVgeEIusg%3D%3D&gclid=Cj0KCQjwvIT5BRCqARIsAAwwD-QNYlkWxNM8pCuN66PljLKYQis72U-sCM82bPkkNtZIgRbKoTCLkaUaAk3UEALw_wcB -> slightly more expensive, but another option

### Drone Dojo's "Raspberry Pi Drone - a Complete Drone Kit"

Link: https://dojofordrones.com/raspberry-pi-drone/

This source goes through building a drone around your Raspberry Pi (from scratch), but also details power sources and useful drone software.

- This guide uses velcro, zip ties, and double-sided tape to attach hardware to the frame

- What is our drone's thrust to weight ratio? How would the addition of the Raspberry Pi change that?

- Things like Ardupilot build Linux-based flight controllers... but we already have a remote control for our drone.  Potentially could look into this to develop self-piloted drone (using a stepwise method to move along pollutant gradients?)

- This website also has a "drone programming primer" (https://dojofordrones.teachable.com/p/drone-programming-primer-for-software-development) that is a 99 USD course; just good to know about.

### Drone Dojo's "Open Source Drone Software Projects"

Link: https://dojofordrones.com/open-source-drone/

This source gives background on Ardupilot and PDX, the two most prevalent open sources for drone code.

- Ardupilot was originally developed for Arduino (but seems to have expanded beyond) which means it is definitely compatible with the Pi, just may take some fanagaling

- PX4 is part of the Linux Foundation and provides an operating system upon which to build drone code

- PX4 doesn't require you to push your code back to the source, so it's more compatible for intellectual property than Ardupilot is

- Ardupilot started in Dronecode (which is the project PX4 is a part of) but then went renegade; as a result, PX4 is better funded

- Both Ardupilot and PX4 are useful for autonomous drones

- Betaflight is largely a quadracopter code source for remote-controlled quadracopters (!!! this might be the best option for us until we reach a point where we want to go autonomous)

- Betaflight is "supported on any autopilot hardware board using at least a STM32F3 processor"

- Librepilot and Cleanflight are other options similar to Betaflight

### Drone Dojo's "ArduPilot Introduction"

Link: https://www.youtube.com/watch?list=PLgiealSjeVyx3t4N9GroE29SbVwhYrOtL&v=jfP71egUpg8

This video specifically talks about ArduPilot, but is part of a playlist that goes into all sorts of information about programming drones that may be relevant to us later.

Once again, Ardupilot is more autonomous than it is remote-controlled, but this could be cool further down the line.

### Instructable's "Drone Pi"

Link: https://www.instructables.com/id/The-Drone-Pi/

This is the details of a project done by students in France. Definitely has a school project vibe, but goes into the process of building a drone.  Again, this isn't quite what we're doing, but it does describe the way that they mount the Pi, as well as how they get the drone connected to Wifi.

- They use a mounting pad (link is unfortunately broken), Wifi key, and a USB key to save their data (which is a video... I think our Pi would be able to store sensor sample measurements in CSV form without a USB)

- Use an "anti-vibration pad"? What is this?

- They set up their programs to automate at boot with crontab -e, which I tried and it didn't work for me.  Why?

### Vjaunet's "QUADCOPTER" Github code

Link: https://github.com/vjaunet/QUADCOPTER

### Erlerobot's "ros_erle_takeoff_land" Github code

Link: https://github.com/erlerobot/ros_erle_takeoff_land

### Device Plus' "DIY Raspberry Pi Drone Mechanics"

Link: https://www.deviceplus.com/raspberry-pi/diy-raspberry-pi-drone-mechanics-part-1/

- These people use a wifi dongle, and also (interestingly) use a suction-cup cell phone holder for a car to attach their phone to their controller, but this seems like it might also work for the Pi?

- They attach the Pi itself with hot glue, which does not seem conducive to removing the Pi at any given point.  So far, I like the velcro on the anti-vibration pad the best.

### Thingiverse's "Flamewheel f450 Anti-Vibration Raspberry Pi 3 and Navio 2 Mount"

Link: https://www.thingiverse.com/thing:2083427 

These people made their own anti-vibration mount to connect their Pi to a drone.

### Anti-Vibration Mounts on Amazon

https://www.amazon.com/Anti-Vibration-Vibration-Absorber-Controller-Quadcopter/dp/B07FKG339P

https://www.amazon.com/Hobbypower-Anti-vibration-Phantom-Vision-Walkera/dp/B00MGIZSMY/ref=pd_lpo_21_t_0/132-8264944-1614032?_encoding=UTF8&pd_rd_i=B00MGIZSMY&pd_rd_r=798f92b6-be9c-4775-b069-356ed5d34254&pd_rd_w=UDcjO&pd_rd_wg=STqhH&pf_rd_p=7b36d496-f366-4631-94d3-61b87b52511b&pf_rd_r=ZTVC65P9FQHPZV2MMYQ3&psc=1&refRID=ZTVC65P9FQHPZV2MMYQ3
