---
title: "BME280 Temperature Sensor"
author: "Anna Madison Burns"
date: "6/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Materials Needed

- 1 BME280 temperature, humidity, and pressure sensor
- 1 Solderless breadboard
- 1 Header strip
- 4 M-F extension jumper wires
- 1 Raspberry pi monitor
- Some sort of interface for your Raspberry Pi (either remote access or HTML connection to a monitor, see the Raspberry Pi guide for instructions)

## Helpful Resources

For diagrams and images, please refer to the following links.

On attaching the sensor to the breadboard: https://learn.adafruit.com/adafruit-bme280-humidity-barometric-pressure-temperature-sensor-breakout/assembly 

On wiring and programming the sensor: https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/i2c-sensors-and-devices 

## Physical Assembly

1.  Take the header strip and break off the number of pins needed for your sensor (for the BME280, this should be seven).

2.  Place the header strip -- long pins facing down -- into the breadboard between D2 and D8 (note: you can place the header strip and sensor elsewhere on your breadboard, but you will need to adjust the wiring instructions below, which assume you are using the setup within these instructions).

3.  Place holes on the sensor onto the short pins facing upwards on the header strip.  Orient the sensor so that it falls over the f-h rows on the breadboard.

4.  Solder the short pins into the temperature reader as per the instructions in the "solder guide" document.

5.  Assemble the M-F wires, attaching the male end to the breadboard and the female end to the Raspberry Pi as follows:

- BB [breadboard] A2 to RP [Raspberry Pi] 1

- BB A4 to RP 6

- BB A5 to RP 5

- BB A7 to RP 3

6.  Connect the Raspberry Pi to power.

## Programming

1.  Turn on I2C interfacing capabilities on your Pi by typing "sudo raspi-config", then select option 5 ("Interfacing options").  Next select P5 ("I2C") and it will ask "would you like the ARM I2C interface to be enabled?" Select yes, and then exit.

2.  To ensure that your Pi can read your sensor, run "sudo i2cdetect -y 1". 

3.  Install the correct library with "pip3 install adafruit-circuitpython-bme280".  Additionally, update the package before the first time you use it with "pip3 install --upgrade adafruit_blinka".

4.  Import the following code into a text file by using the nano function, typing "nano bme280.py".  (Incidentally, bme280.py will also be the name of your text file).  Enter the code into the file and save it using Ctrl O, and then exit the file with Ctrl X.

```{python, eval=FALSE, python.reticulate=FALSE}
import time
import csv
import board
import busio
import adafruit_bme280
 
# Create library object using our Bus I2C port
i2c = busio.I2C(board.SCL, board.SDA)
bme280 = adafruit_bme280.Adafruit_BME280_I2C(i2c)
 
# OR create library object using our Bus SPI port
# spi = busio.SPI(board.SCK, board.MOSI, board.MISO)
# bme_cs = digitalio.DigitalInOut(board.D10)
# bme280 = adafruit_bme280.Adafruit_BME280_SPI(spi, bme_cs)
 
# change this to match the location's pressure (hPa) at sea level
bme280.sea_level_pressure = 1013.25

# create a csv file to save your data to
def  write_to_csv():
        if __name__ == "__main__":
                with open('/home/pi/bme280_data.csv', mode='a') as csv_file: # First condition is the name and location of your csv file (this can be changed); second condition is the 'append' mode, which allows you to add new lines to the document without overwriting old ones
                        csv_writer = csv.writer(csv_file)
                        csv_writer.writerow([bme280.temperature, bme280.humidity, bme280.pressure, bme280.altitude]) # This is your data
                with open('/home/pi/bme280_data.csv', mode='r') as csv_file: # Now that your csv file is appended, this allows you to read it and actually prints the output
                        csv_reader = csv.reader(csv_file)
                        for row in csv_reader:
                                print(row)
 
while True:
    print("\nTemperature: %0.1f C" % bme280.temperature)
    print("Humidity: %0.1f %%" % bme280.humidity)
    print("Pressure: %0.1f hPa" % bme280.pressure)
    print("Altitude = %0.2f meters" % bme280.altitude)
    write_to_csv()
    time.sleep(10)
```

4.  Now, you can run your code by running the line "python3 bme280.py".  It should provide an output for temperature, humidity, and pressure every ten seconds.  You can also access the data from the sensor in the "bme280_data.csv" within your document reader within the "pi" folder. 






