---
title: "NO2_Sensors"
author: "Anna Madison Burns"
date: "6/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Our Sensor

We are using a MiCS-2714 from SGX Sensortech, which costs 8.75 USD.  In addition to the sensor, we also purchased the accompanying MiCS Quickstart Evaluation Board from SGX Sensortech for 38.75 USD.  Furthermore, we have the corresponding HTU21D humidity and temperature sensor, which was purchaed from SGX Sensortech for 2.60 USD.  

Because our sensor produces analog data, but our Pi reads digital data, we need an analog to digital convertor.  We are using the MCP3008 Raspberry Pi Interface, which costs 5.99 USD from Amazon. 

Finally, because the sensor output is 3.3V but the ADC reader can only interpret 5V messages, we need a logic-level convertor to transition the energy from 3.3V to 5V.  This is available under the name Cylewet 10Pcs 2 Channel Logic Level Convertor 3.3V to 5V TTL Module for Arduino, produced by Aloway and available via Amazon for 9.39 USD.

The idea is that the MiCS-2714 sensor outputs a 3.3V analog data reading of NO2 levels in the air; this signal needs to be converted to 5V by the logic level convertor before being read by the MCP3008 analog-digital convertor, which then translates the analog signal into a digital signal that can then be read by our Raspberry Pi.  Therefore, we have three pieces of hardware that we need to wire before we can read the NO2 levels in our environment!

# Materials Needed

* 1 MiCS-2714 NO2 sensor
* 1 MiCS Quickstart Evaluation Board
* 1 jumper
* 1 breadboard
* 1 MCP3008 ADC convertor
* 1 5V to 3.3V logic level convertor
* 9 M-M extension jumper wires
* 5 M-F extension jumper wires

# Before We Begin

Take a look at your breadboard.  The way this works, is that each of the horizontal rows in the middle (for example, 60A-E) are wired together.  That means placing input from a pin in 60A can be read and converted to output by a pin in 60E.  Similarly, the + and - columns on the far edges are connected, but vertically rather than horizontally.

For this project, assign three of the four +/- vertical rows to three outputs: 5V, 3.3V, and GND.  It is useful to label these in pen on the breadboard itself.  I will reference your "breadboard 5V", etc. ... these are referring to your labeled vertical row.  

Doing this allows us to have multiple peices connected to our Raspberry Pi which all use the single 3.3V power source.

# Wiring the Analog to Digital Convertor

To set up our Adafruit MCP3008 ADC, we will use the Adafruit Github packages.  More information on this process is available at https://learn.adafruit.com/raspberry-pi-analog-to-digital-converters/mcp3008.  

Make sure the Raspberry Pi is not connected to power as you complete these steps.

1.  Remove the MCP3008 from the packaging, and find the half-circle that is printed on the back of the convertor.  Place the convertor with the pins facing down in rows E and F (going across the gap in the middle of the breadboard) between rows 24 and 31, with the half-circle on row 31.  The direction of the convertor is very important, because each of the pins has a specific purpose.

2.  Place two M-M jumper wires in the breadboard, with one each connecting 31d and 30d to somewhere in the 3.3V vertical row.  

3.  Connect the M end of a M-F jumper wire to somewhere in the 3.3V vertical row, and connect the F end to pin 1 (3.3V) on the Raspberry Pi.  Your convertor is now connected to power!

4.  Place two more M-M jumper wires in the breadboard, with one each connecting 29d and 24d to your GND vertical row. 

5.  Connect the M end of a M-F jumper wire to somewhere in the GND vertical row, and connect the F end to pin 9 (GND) on the Raspberry Pi.  Your convertor is now grounded!

6.  Connect the M end of a M-F jumper wire to 28d on the breadboard; connect the F end to pin 23 (GPIO11/SPI-SCLK) on the Raspberry Pi.

7.  Connect the M end of a M-F jumper wire to 27d on the breadboard; connect the F end to pin 21 (GPIO9/SPI-MISO) on the Raspberry Pi.

8.  Connect the M end of a M-F jumper wire to 26d on the breadboard; connect the F end to pin 19 (GPIO10/SPI-MOSI) on the Raspberry Pi.

9.  Connect the M end of a M-F jumper wire to 24d on the breadboard; connect the F end to pin 24 (GPIO8/SPI-CEO)  on the Raspberry Pi.

10.  Your MCP3008 is now fully connected to your Pi, and you can connect your Pi to a powersource.

## Testing the Digital Connection of the MCP3008

We'll go through this process to download the proper libraries, and to make sure that the MCP3008 is correctly wired.

1.  Open up the Pi terminal, either through a monitor or a remote access connection (for more information on these options, visit the Raspberry Pi Guide).

2.  Download the necessary packages for using the MCP3008 from the Adafruit library with the following commands:

```{python, eval=FALSE, python.reticulate=FALSE}
sudo apt-get update # Make sure your Pi is up-to-date... this can take some time
sudo apt-get install build-essential python-dev python-smbus git # You may already have some of these packages, but re-download just in case
cd ~ # This takes you to the main directory
git clone https://github.com/adafruit/Adafruit_Python_MCP3008.git # This downloads the appropriate packages from Github, and is one of the advantages of using an Adafruit sensor
cd Adafruit_Python_MCP3008 # Changing the directory to the repository we just downloaded
sudo python setup.py install # Install the appropriate library
```

Now we can begin to test whether or not the convertor is properly connected.

3.  Change directories to the example folder within the Adafruit MCP3008 package with

```{python, eval=FALSE, python.reticulate=FALSE}
cd Adafruit_Python_MCP3008/examples
```

4.  Run the test file that the package already wrote for you with

```{python, eval=FALSE, python.reticulate=FALSE}
sudo python simpletest.py
```

The output will be eight columns (for each of the ADC channels on the sensor) with a value of how much power is being sent to each one.  For example, if each column has a value of 1023, then each is receiving the full 3.3 V.  This code will update every half second, so to stop is you need to type Ctrl C.  If the ADC channels are getting power, then you are good to go!

# Wiring the Logic Level Convertor

1.  Make sure that your logic level convertor is properly soldered, and then place it in the breadboard with the TX1 pin in 35d and the TX0 pin in 35G.

2.  Place one end of a M-M connecting wire in 37D; place the other end in the 3.3V vertical row.

3.  Place one end of a M-M connecting wire in 37H; place the other end in the 5V vertical row.

4.  Place one end of a M-M connecting wire in 38H; place the other end in the GND vertical row.

5.  Place one end of a M-M connecting wire in 38D; place the other end in the GND vertical row.

6.  Place one end of a M-M connecting wire in 39D; place the other end in 31G (this connects it to the MCP3008 that we set up earlier).

7.  Place the male end of a M-F connecting wire in the 5V vertical row; connect the female end to pin 4 on the Raspberry Pi.

Now all that is left is to connect your sensor!

# Wiring the MICS Quick Start Board

The MiCS Quickstart Board has internal wiring for multiple MiCS sensors, and makes it much easier to begin working with our MiCS-2714.  The board should come with three jumpers, as well as the board.  Be careful, because the sensor itself is very, very small.

1.  Remove the sensor and quickstart board from the packagining.  Place the sensor into the case at the top right of the board; make sure that it is flush to the sides of the case, so that the metallic strips are connected on either side.

2.  Take one of the jumpers, and place it over the J3 and J4 pins.

3.  The MiCS-2714 sensor uses Vin+, GND, and VoutB:

* Using a M-F jumper wire, connect Vin+ to the 5V vertical row on the breadboard.

* Using a M-F jumper wire, connect GND to the GND vertical row on the breadboard.

* Using a M-F jumper wire, connect VoutB to 39H on the breadboard (corresponding to the RXI input on the logic level convertor).

Now all the assembly is done... all that is left is to code!

# Code for the Sensor

```{python, eval=FALSE, python.reticulate=FALSE}
import spidev
import time
import os
import csv
 
# Open SPI bus
spi = spidev.SpiDev()
spi.open(0,0)
spi.max_speed_hz=1000000
 
# Function to read SPI data from MCP3008 chip
# Channel must be an integer 0-7
def ReadChannel(channel):
  adc = spi.xfer2([1,(8+channel)<<4,0])
  data = ((adc[1]&3) << 8) + adc[2]
  return data
 
# Function to convert data to voltage level,
# rounded to specified number of decimal places.
def ConvertVolts(data,places):
  volts = (data * 3.3) / float(1023)
  volts = round(volts,places)
  return volts
 
# Function to calculate temperature from
# TMP36 data, rounded to specified
# number of decimal places.
def ConvertNO2(data,places):
 
  # ADC Value (their temp sensor)
  # (approx)  Temp  Volts
  #    0      -50    0.00
  #   78      -25    0.25
  #  155        0    0.50
  #  233       25    0.75
  #  310       50    1.00
  #  465      100    1.50
  #  775      200    2.50
  # 1023      280    3.30
  
  # ADC Value (MiCS-2714)
  # (approx)  NO2   Volts
  #    0       .05    0
  #   78      
  #  155
  #  233
  #  310
  #  465
  #  775
  # 1023      10     3.30
 
  NO2 = ((data * 10.05)/float(1023))+0.05
  NO2 = round(NO2,places)
  return NO2
 
# Define sensor channels
NO2_channel = 0
 
# Define delay between readings
delay = 10
 
# Define the csv where you are storing your data
def  write_to_csv(): # Writes the output to a csv file
        if __name__ == "__main__":
                with open('/home/pi/mics2714_data.csv', mode='a') as csv_file: # First condition is the name and location of your csv file (this can be changed); second condition is the 'append' mode, which allows you to add new lines to the document without overwriting old ones
                        csv_writer = csv.writer(csv_file)
                        csv_writer.writerow([NO2_level,NO2_volts,NO2]) # What your output is titled
                with open('/home/pi/mics2714_data.csv', mode='r') as csv_file: # Now that your csv file is appended, this allows you to read it and actually prints the output
                        csv_reader = csv.reader(csv_file)
                        for row in csv_reader:
                                print(row)
while True:
 
  # Read the temperature sensor data
  NO2_level = ReadChannel(NO2_channel)
  NO2_volts = ConvertVolts(NO2_level,2)
  NO2       = ConvertTemp(NO2_level,2)
 
  # Print out results
  print "--------------------------------------------"
  print("Temp : {} ({}V) {} ppm".format(NO2_level,NO2_volts,NO2))
  write_to_csv()
  
  # Wait before repeating loop
  time.sleep(delay)

```

This code will output the NO2 levels in the air in three different forms: the ADC value (the analog reading), the voltage value (the MCP3008 reading), and finally the parts per million (the data we can actually use).  It will save to a csv file entitled "mics2714_data.csv", which can then be utilized.

### SPI input

Original code from https://www.raspberrypi-spy.co.uk/2013/10/analogue-sensors-on-the-raspberry-pi-using-an-mcp3008/ 

```{python, eval=FALSE, python.reticulate=FALSE}
import spidev
import time
import os
 
# Open SPI bus
spi = spidev.SpiDev()
spi.open(0,0)
spi.max_speed_hz=1000000
 
# Function to read SPI data from MCP3008 chip
# Channel must be an integer 0-7
def ReadChannel(channel):
  adc = spi.xfer2([1,(8+channel)<<4,0])
  data = ((adc[1]&3) << 8) + adc[2]
  return data
 
# Function to convert data to voltage level,
# rounded to specified number of decimal places.
def ConvertVolts(data,places):
  volts = (data * 3.3) / float(1023)
  volts = round(volts,places)
  return volts
 
# Function to calculate temperature from
# TMP36 data, rounded to specified
# number of decimal places.
def ConvertTemp(data,places):
 
  # ADC Value
  # (approx)  Temp  Volts
  #    0      -50    0.00
  #   78      -25    0.25
  #  155        0    0.50
  #  233       25    0.75
  #  310       50    1.00
  #  465      100    1.50
  #  775      200    2.50
  # 1023      280    3.30
 
  temp = ((data * 330)/float(1023))-50
  temp = round(temp,places)
  return temp
 
# Define sensor channels
light_channel = 0
temp_channel  = 1
 
# Define delay between readings
delay = 5
 
while True:
 
  # Read the light sensor data
  light_level = ReadChannel(light_channel)
  light_volts = ConvertVolts(light_level,2)
 
  # Read the temperature sensor data
  temp_level = ReadChannel(temp_channel)
  temp_volts = ConvertVolts(temp_level,2)
  temp       = ConvertTemp(temp_level,2)
 
  # Print out results
  print "--------------------------------------------"
  print("Light: {} ({}V)".format(light_level,light_volts))
  print("Temp : {} ({}V) {} deg C".format(temp_level,temp_volts,temp))
 
  # Wait before repeating loop
  time.sleep(delay)

```

# Helpful Resources for Setting Up Sensor

https://www.instructables.com/id/Smart-Sensor/ - contains link to downlaod pdf on MiCS-2714 (**this was probably the most helpful source I found**) 

https://download.mikroe.com/documents/datasheets/MiCS-2714%20Datasheet.pdf - Datasheet for the sensor

https://sgx.cdistore.com/datasheets/sgx/load-resistance-for-mics-sensors-measurements.pdf - "How to set up load resistance for MiCS sensors measurements"

https://www.sgxsensortech.com/content/uploads/2014/08/AN2-%e2%80%93-Frequently-Asked-Questions-for-MiCS-Gas-Sensors.pdf - "Frequently asked questions for MiCS gas sensors"

https://www.sgxsensortech.com/content/uploads/2014/08/AN-0172-SGX-Metal-Oxide-Gas-Sensors-V1.pdf - "SGX metal oxide sensors (how to use them and how they perform)"

## Scientific Papers that Use a Similar Setup

http://ijiet.com/wp-content/uploads/2018/01/3.pdf - "IOT based indoor air pollution monitor using Raspberry Pi" (paper that uses this sensor with Raspberry Pi)

https://www.mdpi.com/1424-8220/10/6/5469/htm - "Metal oxide semi-conductor gas sensors in environmental monitoring"

https://iopscience.iop.org/article/10.1088/1757-899X/536/1/012050/pdf - "Monitoring system for organic fertilizer plant controller using solar energy" (paper that uses this sensor with Raspberry Pi)


