---
title: "O3 Sensors"
author: "Anna Madison Burns"
date: "6/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Our Sensor

We are using a MQ-131 Ozone Concentration Sensor from Beaster, which costs 42.99 USD on Amazon.  The MQ-131 comes with a high concentration and low concentration ozone sensor, as well as ten input/output pins that must be soldered.  To connect the MQ-131 to the Raspberry Pi, it is also necessary to use a logic level convertor and analog to digital convertor; the LLC is necessary because the MQ-131 requires 5 volts of power while the Pi's GPIOs can only process 3.3 volt signals.  The ADC is necessary because while the MQ-131 emits an analog signal, the Pi can only interpret a digital signal.

# Helpful Resources

The following resource has a guide for the MQ-X sensor, which can be read to understand the ways that MQ sensors work in general:

https://tutorials-raspberrypi.com/configure-and-read-out-the-raspberry-pi-gas-sensor-mq-x/

This is the datasheet for the MQ-131:

https://aqicn.org/air/view/sensor/spec/o3.winsen-mq131.pdf

# Materials Needed

* 1 MQ-131 O3 high/low concentration sensor
* 1 analog to digital convertor (ADC)
* 1 logic level convertor (LLC)
* 1 Raspberry Pi
* 1 breadboard
* 1 soldering gun (and associated solder)
* 4 F-F connecting wires
* 1 M-F wires
* 1 M-M connecting wire

# Physical Assembly

Like all sensors, at the most basic the MQ-131 needs a power source, a ground, and an output; the MQ-131 is complicated a bit by the fact that it is really two sensors in one - a high concentration and low concentration sensor.  The following setup attached a power source and ground to each of the sensors, but has a single output that then allows you to easily switch whether you want a reading from the high concentration or the low concentration sensor.  In indoor, cooler temperature locations a low concentration reading will be more accurate; in higher temperatures or outdoors, the high concentration reading will be more accurate.  Assuming that you will be setting the sensor up inside, the following guide shows you how to connect the sensor to read low concentrations of ozone.

To begin, you will need to solder the MQ-131 - note that because of the size of the sensor, it is uneconomical to place it on the breadboard; reserve that for the ADC and LLC.  Instead, solder so that the longer pins are sticking up out of the MQ-131 and you are soldering the shorter pins from the bottom.  Notice as you are soldering the labels on each of pins, because these will be important for later wiring.

The following assumes that you already have your ADC and LLC wired; for more details on how to do this, visit the "Air Quality Station" SOP.

1.  Using two F-F connecting wires, connect each of the pins labeled "GND" on the MQ-131 to a grounding source, whether that be on the Pi itself or through a breadboard (in which case, adjust the type of connecting wires you are using).

2.  Using two more F-F connecting wires, connect each of the pins labeled "VCC" on the MQ-131 to a 5 volt power source, once again either on the Pi itself or through a breadboard connection.

3.  Using a M-F connecting wire, connect the "OUTL" pin on the MQ-131 (low concentration ouput, as compared to "OUTH" which is high concentration output) to a RX1 terminal on the LLC via a breadboard.

**Note that if you want a high concentration output reading, all you need to do is switch the connecting wire from the "OUTL" pin to the "OUTH" pin on the MQ-131 sensor**

4.  Using a M-M connecting wire, connect the corresponding RX0 terminal (across from the RX0 terminal where you connected the sensor) on the LLC to channel 1 on the ADC.  You can connect it to another channel, but you will need to adjust the code below accordingly to read "O3_Channel=#".  

5.  Connect your Pi to power.

The first time you run the sensor, run the code below for 48 hours to give the sensor time to calibrate and produce more accurate readings.

# Programming

Put the following code into your personal favorite python shell in Raspberry Pi - Nano, THONNY, IDLE, etc. and run the document to read the O3 outputs within your environment. 

```{python, eval=FALSE, python.reticulate=FALSE}
import spidev
import time
import os
import csv
 
# Open SPI bus
spi = spidev.SpiDev()
spi.open(0,0)
spi.max_speed_hz=1000000
 
# Function to read SPI data from MCP3008 chip
# Channel must be an integer 0-7
def ReadChannel(channel):
  adc = spi.xfer2([1,(8+channel)<<4,0])
  data = ((adc[1]&3) << 8) + adc[2]
  return data
 
# Function to convert data to voltage level,
# rounded to specified number of decimal places.
def ConvertVolts(data,places):
  volts = (data * 3.3) / float(1023)
  volts = round(volts,places)
  return volts
 
# Function to calculate temperature from
# TMP36 data, rounded to specified
# number of decimal places.
def ConvertO3(data,places):
 
  # ADC Value (their temp sensor)
  # (approx)  Temp  Volts
  #    0      -50    0.00
  #   78      -25    0.25
  #  155        0    0.50
  #  233       25    0.75
  #  310       50    1.00
  #  465      100    1.50
  #  775      200    2.50
  # 1023      280    3.30
  
  # ADC Value (MQ-131)
  # (approx)  O3    Volts
  #    0       1    0
  #   78      
  #  155
  #  233
  #  310
  #  465
  #  775
  # 1023    1000   3.30
 
  O3 = ((data * 1001)/float(1023))+1
  O3 = round(O3,places)
  return O3
 
# Define sensor channels
O3_channel = 1
 
# Define delay between readings
delay = 10
 
# Define the csv where you are storing your data
def  write_to_csv(): # Writes the output to a csv file
        if __name__ == "__main__":
                with open('/home/pi/mq131_data.csv', mode='a') as csv_file: # First condition is the name and location of your csv file (this can be changed); second condition is the 'append' mode, which allows you to add new lines to the document without overwriting old ones
                        csv_writer = csv.writer(csv_file)
                        csv_writer.writerow([O3_level,O3_volts,O3]) # What your output is titled
                with open('/home/pi/mq131_data.csv', mode='r') as csv_file: # Now that your csv file is appended, this allows you to read it and actually prints the output
                        csv_reader = csv.reader(csv_file)
                        for row in csv_reader:
                                print(row)
while True:
 
  # Read the temperature sensor data
  O3_level = ReadChannel(O3_channel)
  O3_volts = ConvertVolts(O3_level,2)
  O3       = ConvertO3(O3_level,2)
 
  # Print out results
  print "--------------------------------------------"
  print("O3 : {} ({}V) {} ppb".format(O3_level,O3_volts,O3))
  write_to_csv()
  
  # Wait before repeating loop
  time.sleep(delay)
```

