---
title: "PM Sensors"
author: "Anna Madison Burns"
date: "6/10/2020"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Our sensor

We are using a Digital Particle Concentration Laser Sensor PMS5003 PM2.5 PM10+Cable for Arduino from Amazon, which costs 38.75 USD.  This sensor comes with eight female-to-female connectors as well as an adapter for Arduino or Raspberry Pi, and a connector for the Raspberry Pi and the adapter itself.  

## Helpful resource

The guide below was compiled from an instructional Youtube video published on 11 January 2019 by Chengyi Wu.  While the video is not in English, it is easy to follow along both with the physical construction and code for the PMS5003:  https://www.youtube.com/watch?v=B0bzyEnjZY4 

# Physically connecting the sensor to Raspberry Pi

1.  Begin by connecting the sensor to the adapter. Take the colorful wires with white blocks on either end and attach them to both the sensor and the small adapter; they attach with the "shiny" side up, and you need to give them quite a push to get them to go in fully.  They should be snug, and not at all loose.

2.  Next, connect the adapter to the Raspberry Pi.  Separate four of the female-to-female connectors (the ones with the black rectangles on either end) and attach one of the ends to the TXD, RXD, GND and VCO terminals on the adapter (these correspond to the 4th, 5th, 7th, and 8th terminals from the top).  

  2a.  Connect the wire attached to the VCC terminal to node 2 on the Raspberry Pi.

  2b.  Connect the wire attached to the GND terminal to node 14 on the Raspberry Pi.

  2c.  Connect the wire attached to the RXD terminal to node 8 on the Raspberry Pi.

  2d.  Connect the wire attached to the TXD terminal to node 10 on the Raspberry Pi.

3.  Connect your Pi to power, and your sensor is good to go!

# Coding the PM10 sensor into Raspberry Pi

I did this entire step within the Raspberry Pi terminal interface.  

## Preliminary steps

1.  Enter "sudo raspi-config".

2.  Select option 5 ("Interfacing Options").

3. Enable ARM I2C by selecting it in this menu and then pressing Yes.

4. Then to enable Serial, choose Serial on the menu. 

5. A window will pop up asking, "would you like a login shell to be accessible over serial?", and the answer is NO.

3.  Next, a window will pop up asking, "Would you like the serial port hardware to be enabled?", this time say YES, and exit the window.

5. Click Finish, you may be prompted to reboot, and select YES. 

## Code

1.  Open up a text document in nano by typing "nano pms5003.py" into the bar in the terminal (pms5003.py will be our document name).

2.  Copy the following code to your computer's clipboard using Ctrl C:

```{python, eval=FALSE, python.reticulate=FALSE}
import serial
from collections import OrderedDict
class Sensor():
  def __init__(self, tty = '/dev/ttyS0'):
    self.tty = tty
  
  def open(self):
    self.serial = serial.Serial(self.tty, baudrate = 9600)
  
  def close(self):
    self.serial.close()
    
  def read_bytes(self, data, idx, size = 2):
    return int("".join(data[idx : idx + size]), 16)
    
  def read(self):
    data = self.serial.read(32)
    data = ["{:02X}".format(d) for d in data]
    
    if data[0] != '42' or data[1] != '4D':
      return None
      
    res = OrderedDict()
    res['pm1_cf'] = self.read_bytes(data, 4)
    res['pm25_cf'] = self.read_bytes(data, 6)
    res['pm10_cf'] = self.read_bytes(data, 8)
    res['pm1'] = self.read_bytes(data, 10)
    res['pm25'] = self.read_bytes(data, 12)
    res['pm10'] = self.read_bytes(data, 14)
    
    res['temperature'] = self.read_bytes(data, 24) / 10
    res['humidity'] = self.read_bytes(data, 26) / 10
    return res
    
if __name__ == '__main__':
  '''
  Test code
  '''
  sensor = Sensor()
  sensor.open()
  data = sensor.read()
  sensor.close()
  print(data)
  
```

A few notes on this Python code:

- Originally was an error in line 85, the colon was left out of the code; added 6/16.
- Double check spacing with line 98... make sure the res line is inside of the def read(self) paragraph.
- Pay very close attention to spacing and indentations! This is very, very important in Python.  The code will not run if the indentations are at all off.

3.  Re-enter the nano file you created above, and right click anywhere within the file to bring up a menu; select the "paste" option.  This should place the code above into the file without altering the spacing or indentations.

4.  Save the text document with ctrl O (it will ask it what you want to name it, you can leave it as pms5003.py), and then exit it with ctrl X.

5.  Now within the main shell, type "python3 pms5003.py".  It should release a reading of the different measurements specified.

## Still to come

- Storing the data somewhere that we can see variability (perhaps Adafruit IO?  Info (for a different PM sensor): https://www.raspberrypi.org/blog/monitor-air-quality-with-a-raspberry-pi/ )

- Getting the Pi to automatically read data when it is on, rather than with a code (might also be information in the above resource)

- Checking for accuracy (why divide the temperature/humidity by ten?)

- Getting it to read onto a Box CSE file ?

- "The Raspberry Pi does not have a Real-Time Clock: on bootstrap it gets the time via NTP protocol over the internet. If an NTP server is not available, it will default to the time of last shutdown. Neverthless the station is supposed to work and store data even when there is not internet connection, so it is required a Real-Time Clock module." -> do we need one of these?


Potential places to store data:
- Luftdaten: a German open-source citizen science data repository for air quality

https://learn.pimoroni.com/tutorial/sandyj/enviro-plus-and-luftdaten-air-quality-station (this tutorial uses a different input w/ enviroplus, so the code is not the same as what we have)

- Into a CSV file: https://stackoverflow.com/questions/57314552/saving-sensor-data-from-pi-into-csv-file (not sure how to tailor this to our project)

```{python, eval=FALSE, python.reticulate=FALSE}
# initial set up of imports

import time
import datetime

# gpiozero for CPU
from gpiozero import CPUTemperature

# imports the modules for the sensor
from bmp280 import BMP280
try:
    from smbus2 import SMBus
except ImportError:
    from smbus import SMBus
    
# lux sensor
import ltr559

# csv to be able to open file
import csv

# sets up the variables for the sensor
bus=SMBus(1)
bmp280 = BMP280(i2c_dev=bus)

# functions to use

def cpu_temperature():
    cpu = CPUTemperature()
    cpu_temp = cpu.temperature
    cpu_temp = str(cpu_temp)
    return(cpu_temp)

def get_temp():
    temperature = bmp280.get_temperature()
    temperature = round((temperature),2)
    temperature = temperature -2
    temperature = str(temperature)
    return(temperature)

def get_pressure():
    pressure = bmp280.get_pressure()
    pressure = round(pressure)
    pressure = str(pressure)
    return(pressure)

def get_lux():
    lux = ltr559.get_lux()
    for x in range(1,5):
        x_lux = lux
        time.sleep(0.5)
    lux_rounded = round(x_lux,2)
    lux_str = str(lux_rounded)
    return(lux_str)

def date_now():
    today = datetime.datetime.now().strftime("%Y-%m-%d")
    today = str(today)
    return(today)

def time_now():
    now = datetime.datetime.now().strftime("%H:%M:%S")
    now = str(now)
    return(now)

def write_to_csv():
    # the a is for append, if w for write is used then it overwrites the file
    with open('/home/pi/twitter_sensor/sensor_readings.csv', mode='a') as sensor_readings:
        sensor_write = csv.writer(sensor_readings, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        write_to_log = sensor_write.writerow([date_now(),time_now(),get_temp(),get_pressure(),get_lux(),cpu_temperature()])
        return(write_to_log)

write_to_csv()
```


- Prometheus -> pulls the data, doesn't automatically get sent it form the device, works well w/ Grafata https://www.markhansen.co.nz/raspberry-pi-air-quality-sensor/ 

- InfluxDB

- PostgreSQL



New:
- Connect RST to pin 11

Code:
Couldn't get this to work after ~1.5 hours of messing around with it, moving on to try to work with the code we already have

```{python, eval=FALSE, python.reticulate=FALSE}
import serial
import datetime
from pymongo import MongoClient

port = serial.Serial('/dev/ttyAMA0', baudrate=9600, timeout=2.0)
client = MongoClient('localhost')


def read_pm_line(_port):
    rv = b''
    while True:
        ch1 = _port.read()
        if ch1 == b'\x42':
            ch2 = _port.read()
            if ch2 == b'\x4d':
                rv += ch1 + ch2
                rv += _port.read(28)
                return rv


loop = 0
while True:
    try:
        rcv_list = []
        rcv = read_pm_line(port)
        res = {'timestamp': datetime.datetime.now(),
               'apm10': rcv[4] * 256 + rcv[5],
               'apm25': rcv[6] * 256 + rcv[7],
               'apm100': rcv[8] * 256 + rcv[9],
               'pm10': rcv[10] * 256 + rcv[11],
               'pm25': rcv[12] * 256 + rcv[13],
               'pm100': rcv[14] * 256 + rcv[15],
               'gt03um': rcv[16] * 256 + rcv[17],
               'gt05um': rcv[18] * 256 + rcv[19],
               'gt10um': rcv[20] * 256 + rcv[21],
               'gt25um': rcv[22] * 256 + rcv[23],
               'gt50um': rcv[24] * 256 + rcv[25],
               'gt100um': rcv[26] * 256 + rcv[27]
               }
        # print('===============\n'
        #       'PM1.0(CF=1): {}\n'
        #       'PM2.5(CF=1): {}\n'
        #       'PM10 (CF=1): {}\n'
        #       'PM1.0 (STD): {}\n'
        #       'PM2.5 (STD): {}\n'
        #       'PM10  (STD): {}\n'
        #       '>0.3um     : {}\n'
        #       '>0.5um     : {}\n'
        #       '>1.0um     : {}\n'
        #       '>2.5um     : {}\n'
        #       '>5.0um     : {}\n'
        #       '>10um      : {}'.format(res['apm10'], res['apm25'], res['apm100'],
        #                                res['pm10'], res['apm25'], res['pm100'],
        #                                res['gt03um'], res['gt05um'], res['gt10um'],
        #                                res['gt25um'], res['gt50um'], res['gt100um']))
        rcv_list.append(res.copy())
        loop += 1
        if loop == 10:
            client.air.pm.insert_many(rcv_list)
            print('Logged to database.')
            rcv_list.clear()
            loop = 0
    except KeyboardInterrupt:
        break
```



