---
title: "Equipment Ordered"
author: "Anna Madison Burns"
date: "6/2/2020"
output:
  html_document:
    df_print: paged
---

# EA 30 Ordering List

- Soldering Iron/Kit, $30.00

https://www.amazon.com/gp/product/B0852XJN11/ref=ppx_yo_dt_b_asin_title_o03_s01?ie=UTF8&psc=1


# Several types of sensors


# MQ-X Sensors


# NO2 Sensors

### MICS-2714

- Manufacturer:  SGX SensorTech

- Source:  CDI Web

- Price:  8.75 USD

- Link:  https://www.cdiweb.com/portalproductdetail.aspx?ProdId=333416&ManufId=364 

- Notes:  MOX Sensor; used in Ripoll et al., accuracy evaluated by Spinelle

### NO2-E350

**Re-evaluate**

- Manufacturer:  CityTech

- Source:  CityTech

- Price:  ? (Inquiry sent)

- Link:  https://www.citytech.com/en-gb/

- Notes:  Need to submit inquiry before ordering; Similar to monitor used in Ripoll but rated by Spinelle to be more effective; Used with uSu-edu board and Raspberry pi 3 by Ripoll; potentially not necessary, re-evaluate when sensor is built

### Enviro for Raspberry Pi

- Manufacturer:  Pimoroni

- Source:  Amazon

- Price: 56.99 USD

- Link:  https://www.amazon.com/gp/product/B07WZJJ8BV/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

- Notes:  Has built in NO2 and temp sensors, very well-built data library and packages

## Associated Parts for NO2 Sensors

### MICS QuickStart Evaluation Board 

- Manufacturer:  SGX SensorTech

- Source: CDI Web

- Price: 38.75 USD

- Link:  https://www.cdiweb.com/products/detail/micsquickstart-sgx-sensortech/486656/

- Notes:  Cheaper equivalent of what was used by Ripoll, can mount both CO2 and NO2 sensors but doesn't have a built-in humidity sensor

### Adafruit MCP3008 Raspberry Pi Interface

- Manufacturer:  Adafruit

- Source:  Amazon

- Price: 5.99 USD

- Link:  https://www.amazon.com/gp/product/B00NAY3RB2/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1 

- Notes: Analog to digital convertor, needed for Ozone and NO2 sensors

### HTU21D (Humidity + Temp Sensor)

**Re-evaluate**

- Manufacturer: SGX Sensortech

- Source: CDI Web

- Price:  2.60 USD

- Link:  https://www.cdiweb.com/products/detail/hpp845e031r4-te-connectivity/558681/

- Notes: Potentially not necessary, re-evaluate after sensor is built

# PM10 Sensors

### Digital Particle Concentration Laser Sensor PMS5003 PM2.5 PM10 + Cable for Arduino 

- Manufacturer:  Ministry of Warehouse (?)

- Source:  Amazon

- Price:  38.75 USD

- Link:  https://www.amazon.com/gp/product/B0787H244V/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

- Notes:  Comes with connectors for Pi and Arduino, as well as conversion board

# Temperature/Humidity Sensors

### Adafruit BME280 I2C or SPI Temperature Humidity Pressure Sensor

- Manufacturer:  3D Makerworld, Inc.

- Source:  Amazon

- Price: 24.96 USD

- Link: https://www.amazon.com/gp/product/B013W1AJUY/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1 

# Ozone Sensors

### Beaster MQ131 Ozone Concentration Sensor High and Low Concentration O3 Air Quality Detection Module

- Manufacturer:  Beaster

- Source:  Amazon

- Price: 42.99 USD

- Link:  https://www.amazon.com/gp/product/B07LGZH46N/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

# Hardware

### ELEGOO 3pcs MB-102 Breadboard 830 Point Solderless Prototype PCB Board Kit for Arduino Proto Shield Distribution Connecting Blocks

- Manufacturer: ELEGOO

- Source: Amazon

- Price: 8.99 USD

- Link: https://www.amazon.com/gp/product/B01EV6LJ7G/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

- Notes: Includes 3 breadboard units

### ELEGOO EL-CP-004 120pcs Multicolored Dupont Wire 40pin Male to Female, 40pin Male to Male, 40pin Female to Female Breadboard Jumper Wires Ribbon Cables Kit for arduino 

- Manufacturer:  ELEGOO

- Source:  Amazon

- Price: 6.98 USD

- Link:  https://www.amazon.com/gp/product/B01EV70C78/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1 

# Time Clocks

### Adafruit 3296 DS1307 Real Time Clock Breakout Board

- Manufacturer:  Adafruit

- Source:  Amazon

- Price: 9.92 USD

- Link:  https://www.amazon.com/gp/product/B01MG3NEWF/ref=ox_sc_act_title_2?smid=AM0JQO74J587C&psc=1

## Associated Parts for Time Clocks

### Energizer CR1220 Low Drain 3V lithuim Battery (pack of 5)

- Manufacturer:  Energizer

- Source:  Amazon

- Price: 6.98 USD

- Link:  https://www.amazon.com/gp/product/B003CU3E2Q/ref=ox_sc_act_title_1?smid=A19DY5EK03NION&psc=1 

